### ISSUE TITLE
.ino file does not compile

### ISSUE THREAD

**Issue by JoniSykes** [nikita-leonov/particleio-homekit#5]
Incomplete if statements.
Deprecated references.
Incorrect result variable cast.

**Comment by nikita-leonov** [comment]
@JoniSykes thanks for reporting This one was an experiment project without further continuation. I should put a deprecated notice into a header. Homebridge and many other dependencies are doing much better job in it in compare with a current solution.

**Comment by JoniSykes** [comment]
Ok no problem. 
I've being trying to follow another guide as well to see if I have any luck there: 
https://github.com/krvarma/HomeKit-and-Particle-Photon
Unfortunately there have been a lot of issues with this as well. 

Do you know of any good tutorials/resources to help me understand the relationship between the exposed functions on the spark/particle -> the accessory defined for homebridge and the homebridge config.json.

I'd be happy to try and update all of this if I get mine working, but given the firmware (which I've fixed) for the core/photon, I can't seem to get the accessory and config right.

**Comment by JoniSykes** [comment]
If it makes a difference to your response, the error I get is when I run homebridge and is as follows:
```
Jonny:~/.homebridge|⇒  homebridge
[1/5/2017, 4:52:59 PM] Loaded plugin: homebridge-particle
[1/5/2017, 4:52:59 PM] Registering platform 'homebridge-particle.Particle'
[1/5/2017, 4:52:59 PM] ---
[1/5/2017, 4:52:59 PM] Loaded config.json with 1 accessories and 0 platforms.
[1/5/2017, 4:52:59 PM] ---
[1/5/2017, 4:52:59 PM] Loading 0 platforms...
[1/5/2017, 4:52:59 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'ParticleAccessory' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by JoniSykes** [comment]
I've recently installed the plugin on the other PR. 
A few adjustments to it and the .ino and it's all working. I'll update both my PR and the plugin PR.
